---
  - hosts: all
    roles:
    - role: ansible-rbenv-role
      vars:
        rbenv:
          env: user
          version: v1.0.0
          default_ruby: 2.4.1
          rubies:
            - version: 2.4.1
              env:
                RUBY_BUILD_CURL_OPTS: "--tlsv1.2"
        rbenv_users:
          - "{{remote_user}}"
