---
  - hosts: all
    roles:
    - role: ansible-gcc-toolbox
    - role: ansible-rbenv-role
      vars:
        rbenv:
          env: user
          version: v1.0.0
          default_ruby: 2.4.1
          rubies:
            - version: 2.4.1
              env:
                RUBY_BUILD_CURL_OPTS: "--tlsv1.2"
        rbenv_users:
          - "{{remote_user}}"
        rbenv_owner: 'deploy'
        rbenv_group: 'deploy'
    - role: ansible-role-mysql-community
      become: yes
      mysql_root_pass: "rJ3780p0KMk="
      mysql_packages:
      - "mysql-devel"
      - "mysql-community-server"
      - "MySQL-python"
